file_cache_path           "/home/pi/setup_pitor/chef-repo"
data_bag_path             "/home/pi/setup_pitor/chef-repo/data_bags"
encrypted_data_bag_secret "/home/pi/setup_pitor/chef-repo/data_bag_key"
cookbook_path             "/home/pi/setup_pitor/chef-repo/cookbooks"
role_path                 "/home/pi/setup_pitor/chef-repo/roles"
