name              "pitor"
maintainer        "Stichting Paraplu"
maintainer_email  "hscholten@paraplu.nl;"
license           "Apache 2.0"
description       "Sets up TOR on Raspberry Pi"
version           "0.1.0"
supports          "wheezy"
recipe            "wheezy", "Sets up TOR for Raspberry Pi"
